export default [
  {
    teamId: 0,
    city: "Sao Paulo",
    name: "Jaguars",
    abbrev: "SP",
    conference: "West",
    division: "South America",
  },
  {
    teamId: 1,
    city: "Buenos Aires",
    name: "Argentina",
    abbrev: "BA",
    conference: "West",
    division: "South America",
  },
  {
    teamId: 2,
    city: "Lima",
    name: "Peru",
    abbrev: "LIMA",
    conference: "West",
    division: "South America",
  },
  {
    teamId: 3,
    city: "Santiago",
    name: "Ballers",
    abbrev: "STGO",
    conference: "West",
    division: "South America",
  },
  {
    teamId: 4,
    city: "Mexico City",
    name: "Aztecs",
    abbrev: "CDMX",
    conference: "West",
    division: "North America",
  },
  {
    teamId: 5,
    city: "New York",
    name: "Liberty",
    abbrev: "NY",
    conference: "West",
    division: "North America",
  },
  {
    teamId: 6,
    city: "Toronto",
    name: "Blizzard",
    abbrev: "TOR",
    conference: "West",
    division: "North America",
  },
  {
    teamId: 7,
    city: "Los Angeles",
    name: "Earthquakes",
    abbrev: "LA",
    conference: "West",
    division: "North America",
  },
  {
    teamId: 8,
    city: "Cairo",
    name: "Pharoahs",
    abbrev: "CAI",
    conference: "West",
    division: "Africa",
  },
  {
    teamId: 9,
    city: "Lagos",
    name: "Hyenas",
    abbrev: "LA",
    conference: "West",
    division: "Africa",
  },
  {
    teamId: 10,
    city: "Kinshasa",
    name: "Lions",
    abbrev: "KIN",
    conference: "West",
    division: "Africa",
  },
  {
    teamId: 11,
    city: "Johannesburg",
    name: "Meerkats",
    abbrev: "JHB",
    conference: "West",
    division: "Africa",
  },
  {
    teamId: 12,
    city: "Moscow",
    name: "Bears",
    abbrev: "MSK",
    conference: "West",
    division: "European",
  },
  {
    teamId: 13,
    city: "Paris",
    name: "Musketeers",
    abbrev: "PAR",
    conference: "West",
    division: "European",
  },
  {
    teamId: 14,
    city: "London",
    name: "Royals",
    abbrev: "LDN",
    conference: "West",
    division: "European",
  },
  {
    teamId: 15,
    city: "Madrid",
    name: "Bulls",
    abbrev: "MD",
    conference: "West",
    division: "European",
  },
  {
    teamId: 16,
    city: "Karachi",
    name: "Immortals",
    abbrev: "KHI",
    conference: "East",
    division: "Middle East",
  },
  {
    teamId: 17,
    city: "Tehran",
    name: "Iran",
    abbrev: "THR",
    conference: "East",
    division: "Middle East",
  },
  {
    teamId: 18,
    city: "Istanbul",
    name: "Falcons",
    abbrev: "IST",
    conference: "East",
    division: "Middle East",
  },
  {
    teamId: 19,
    city: "Riyadh",
    name: "Princes",
    abbrev: "RUH",
    conference: "East",
    division: "Middle East",
  },
  {
    teamId: 20,
    city: "Singapore",
    name: "Pirates",
    abbrev: "SG",
    conference: "East",
    division: "Island",
  },
  {
    teamId: 21,
    city: "Jakarta",
    name: "Sharks",
    abbrev: "JKT",
    conference: "East",
    division: "Island",
  },
  {
    teamId: 22,
    city: "Sydney",
    name: "Devils",
    abbrev: "SYD",
    conference: "East",
    division: "Island",
  },
  {
    teamId: 23,
    city: "Kuala Lumpur",
    name: "Dolphins",
    abbrev: "KL",
    conference: "East",
    division: "Island",
  },
  {
    teamId: 24,
    city: "Delhi",
    name: "Bengals",
    abbrev: "DL",
    conference: "East",
    division: "South",
  },
  {
    teamId: 25,
    city: "Bangkok",
    name: "Elephants",
    abbrev: "BKK",
    conference: "East",
    division: "South",
  },
  {
    teamId: 26,
    city: "Hanoi",
    name: "Vietnam",
    abbrev: "HN",
    conference: "East",
    division: "South",
  },
  {
    teamId: 27,
    city: "Dhaka",
    name: "Bangladesh",
    abbrev: "DAC",
    conference: "East",
    division: "South",
  },
  {
    teamId: 28,
    city: "Tokyo",
    name: "Samurai",
    abbrev: "TYO",
    conference: "East",
    division: "Far East",
  },
  {
    teamId: 29,
    city: "Manila",
    name: "Typhoons",
    abbrev: "MLA",
    conference: "East",
    division: "Far East",
  },
  {
    teamId: 30,
    city: "Shanghai",
    name: "Dragons",
    abbrev: "SHG",
    conference: "East",
    division: "Far East",
  },
  {
    teamId: 31,
    city: "Seoul",
    name: "Dynasty",
    abbrev: "SEL",
    conference: "East",
    division: "Far East",
  },
];
